### ISSUE TITLE
pruneTable.txt in TableGenerator.java

### ISSUE THREAD

**Issue by haiduc32** [HaginCodes/3x3x3-Image-processing#1]
Hi,

I'm trying to use your code but I found a reference to a pruneTable.txt file in TableGenerator.java, but I can't find the file, and there is no such file generated on the fly. How can I get that file?

thanks

**Comment by thatc0der** [comment]
Yeah you aren't supposed to run TableGenerator.Java as I already created the tables and they are the txt files in the repo.  All you need to do is run MainFrame.java. I have the instructions listed in the readme

**Comment by thatc0der** [comment]
Let me know if this helps or if you still are wondering how to get it working,
